version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8087:80"
    volumes:
      - ./challenge:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - net

  php:
    image: php:7-fpm
    expose:
      - "9000"
    volumes:
      - ./challenge:/var/www/html
    networks:
      - net

  redis:
    image: redis:6.2
    expose:
      - "6379"
    networks:
      - net

networks:
  net:
    driver: bridge
